dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

install: pip install oci pytest-mock pytest-asyncio pyyaml ansible-lint mypy requests_mock

script:
  - pytest
  - ansible-lint compute.yml
  - mypy roles/slurm/files/citc_oci.py
