---

- name: Add InfluxDB repository
  yum_repository:
    name: influxdb
    description: InfluxDB
    baseurl: https://repos.influxdata.com/centos/$releasever/$basearch/stable/
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: install telegraf package
  yum:
    name:
      - telegraf
  notify: restart telegraf

- name: enable the telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes

- name: enable network monitoring in telegraf
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.net]"
    option: interfaces
    value: '["*"]'
    state: present
  notify: restart telegraf

- name: install influxdb package
  yum:
    name:
      - influxdb
  notify: restart influxdb
  when: monitoring_role == "master"

- name: enable the influxdb service
  service:
    name: influxdb
    state: started
    enabled: yes
  when: monitoring_role == "master"

- name: configure telegraf to use InfluxDB URL
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[outputs.influxdb]"
    option: urls
    value: '["http://mgmt:8086"]'
    backup: yes
  notify: restart telegraf

- name: Add Grafana repository
  yum_repository:
    name: grafana
    description: Grafana
    baseurl: https://packages.grafana.com/oss/rpm
    gpgkey: https://packages.grafana.com/gpg.key
  when: monitoring_role == "master"

- name: install grafana package
  yum:
    name:
      - grafana
  notify: restart grafana
  when: monitoring_role == "master"

- name: enable the grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
  when: monitoring_role == "master"

- name: open Grafana port in firewall
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
  when: monitoring_role == "master"
  notify:
    - restart firewalld

- name: Check admin password
  uri:
    url: http://localhost:3000/api/admin/settings
    user: admin
    password: "{{ grafana_admin_password }}"
    force_basic_auth: yes
  ignore_errors: yes
  register: grafana_password
  when: monitoring_role == "master"

- name: Set admin password
  uri:
    url: http://localhost:3000/api/user/password
    user: admin
    password: admin
    force_basic_auth: yes
    method: PUT
    body_format: json
    body: '{ "oldPassword": "admin", "newPassword": "{{ grafana_admin_password }}", "confirmNew": "{{ grafana_admin_password }}"}'
  ignore_errors: '{{ ansible_check_mode }}'
  when:
    - monitoring_role == "master"
    - grafana_password.status == 401

- name: create get_secrets script
  copy:
    dest: /home/opc/get_secrets
    content: |
      #! /bin/bash
      echo "{{ grafana_admin_password }}"
    owner: opc
    mode: 0700
  when: monitoring_role == "master"

- name: Create influxdb telegraf datasource
  grafana_datasource:
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: "{{ grafana_admin_password }}"
    name: influxdb_telegraf
    ds_type: influxdb
    url: http://localhost:8086
    database: telegraf
  when: monitoring_role == "master"

- name: install monitor_slurm script
  copy:
    dest: /usr/local/bin/monitor_slurm
    content: |
      #! /bin/bash
      set -euo pipefail
      IFS=$'\n\t'

      data=$(sinfo --noheader --Format=StateLong,Nodes)

      values=""

      for i in $data
      do
        state=$(echo $i | awk '{print $1}')
        count=$(echo $i | awk '{print $2}')
        values+=",${state}=${count}"
      done

      if [[ ! -z "${values}" ]]
      then
        echo "nodestatuscount ${values:1}"
      fi
    mode: a=rx,u+w
  when: monitoring_role == "master"

- name: enable slurm monitoring in influx
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.exec]"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ keys|dict2items }}"
  vars:
    keys:
      commands: '["/usr/local/bin/monitor_slurm"]'
      timeout: '"5s"'
      name_suffix: '"_slurm"'
      data_format: '"influx"'
  notify: restart telegraf

- name: Copy in Slurm Grafana dashboard
  template:
    src: slurm_dashboard.json.j2
    dest: /etc/citc/slurm_dashboard.json
  when: monitoring_role == "master"

- name: Download Telegraf dashboard
  get_url:
    url: https://grafana.com/api/dashboards/928/revisions/3/download
    dest: /etc/citc/928.json

- name: Set Influx datasource
  replace:
    path: /etc/citc/928.json
    regexp: '\${DS_INFLUXDB_TELEGRAF}'
    replace: 'influxdb_telegraf'

- name: Import dashboard
  copy:
    dest: /etc/grafana/provisioning/dashboards/citc.yaml
    content: |
      apiVersion: 1

      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
        options:
          path: /etc/citc/
  notify: restart grafana
  when: monitoring_role == "master"
