---
- name: Install epel-release
  yum:
    name: "{{ epel_release_rpm }}"
    state: present

- name: Enable OpenHPC Intel Arch Base repository for local use
  shell: yum-config-manager --add-repo={{ ohpc_release_base_rpm_intel }}
  args:
    creates: /etc/yum.repos.d/OpenHPC:1.3.repo

- name: Enable OpenHPC Intel Arch Update 7 repository for local use
  shell: yum-config-manager --add-repo={{ ohpc_release_updates_rpm_intel }}
  args:
    creates: /etc/yum.repos.d/OpenHPC:1.3:Update7.repo

- name: Lmod
  yum:
    name: "lmod-ohpc"
    state: present

- name: Install the lmod-defaults package on master and a development node
  yum: name="{{item}}" state=present
  with_items:
  - "{{ ohpc_lmod_mpi_default }}"
  - gnu8-compilers-ohpc.x86_64
  - openmpi3-pmix-slurm-gnu8-ohpc.x86_64
